// <auto-generated />
using System;
using ConvertLogs.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConvertLogs.API.Migrations
{
    [DbContext(typeof(ConvertLogsDbContext))]
    partial class ConvertLogsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConvertLogs.API.Models.LogConvertido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CacheStatus");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("HttpMethod");

                    b.Property<string>("Provider");

                    b.Property<int>("ResponseSize");

                    b.Property<int>("StatusCode");

                    b.Property<int>("TimeTaken");

                    b.Property<string>("UriPath");

                    b.HasKey("Id");

                    b.ToTable("LogsConvertidos");
                });

            modelBuilder.Entity("ConvertLogs.API.Models.LogOrigem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CacheStatus");

                    b.Property<string>("HttpMethod");

                    b.Property<int>("ResponseSize");

                    b.Property<int>("StatusCode");

                    b.Property<double>("TimeTaken");

                    b.Property<string>("UriPath");

                    b.HasKey("Id");

                    b.ToTable("LogsOrigem");
                });
#pragma warning restore 612, 618
        }
    }
}
